### ISSUE TITLE
Verify .xlsx input data

### ISSUE THREAD

**Issue by mwakok** [mitigation-controller/mitc#1]
Add the functionality to check the input data (.xlsx file) on the following errors and exceptions:

- [x] Check file type
- [ ] Check column names
- [ ] Check data types
- [ ] Presence of essential data
- [ ] Presence of optional data
- [ ] optimistic<=likely<=pessimistic
- [ ] minimum umber of simulations is 1000. 5000 is recommended

**Comment by omarkamouh** [comment]
@mwakok I added additional check requirements to the list above.
