### ISSUE TITLE
Handle the issue of student/developer versions of the MitC: a button that automatically set Penalty to infinity and reward to 0 for example

### ISSUE THREAD

**Issue by mwakok** [mitigation-controller/mitc#14]

**Comment by omarkamouh** [comment]
@mwakok We need a button to choose one of the two versions. The student version won't have the penalty/reward inputs. The other version does. Also, the spread sheet of the students should not have the last table that I added (although it wont harm if they don't write anything in it). But it would be good if the student version will load a spreadsheet without the addition table that I added. Let me know what you think..
