### ISSUE TITLE
Documentation for developers

### ISSUE THREAD

**Issue by omarkamouh** [mitigation-controller/mitc#34]

**Comment by omarkamouh** [comment]
@mwakok I suppose it is different from the end user's documentation. Please start by preparing a template or instructions on the best-practices for doing it.  We can start collaboration from there.

**Comment by mwakok** [comment]
Developer and maintenance documentation is now captured in the Wiki. The Wiki pages are just simple markdown pages and could be moved as a document inside the repository if desired.

**Comment by mwakok** [comment]
I have also added a CONTRIBUTING.md document with instructions for contributing to the code.
