### ISSUE TITLE
Add videos to the end-user documentation

### ISSUE THREAD

**Issue by omarkamouh** [mitigation-controller/mitc#35]

**Comment by omarkamouh** [comment]
@mwakok where should I upload the videos? Github or another platform?

**Comment by mwakok** [comment]
Uploading the videos to the GitHub repository would not be preferential as it increases the size of the repository unnecessarily. Also, it is not possible to embed a video natively in a markdown file. The examples I have come across have either uploaded the video to youtube (or other platform) and just provide a link, or have created an embedded gif. Or a combination, such as this [repository](https://github.com/aloisdg/Doccou/blob/master/README.md#demo).

Not sure what to recommend yet. Perhaps you could upload the videos to our Teams channel in the meantime, so I can play around with different solutions.

**Comment by omarkamouh** [comment]
I uploaded the videos on Youtube and I added the links in the documentation together with the published paper #79
