### ISSUE TITLE
Verify that all activities have successors but the "end" activity

### ISSUE THREAD

**Issue by mwakok** [mitigation-controller/mitc#38]

**Comment by omarkamouh** [comment]
If the network is large, connecting end activities to the "end" node is painful. Maybe we could just do it internally in the code so the user does not have to do it. All lose ends are connected to a node that we define internally

**Comment by mwakok** [comment]
- [ ] Remove "End" activity in xlsx data
- [ ] Add function at line 77 in parse_data that adds rowwith end values
- [ ] Add +1 to nActivities

**Comment by mwakok** [comment]
I added a new function `bin/find_missing_predecessors.m` that
- finds all missing predecessor activiteis and add them to the dataCell and dataDouble variables.
- Add +1 to nActivities

The function is called in `modules/parse_data.m` in line 38.
