### ISSUE TITLE
Register the software in a repository

### ISSUE THREAD

**Issue by mwakok** [mitigation-controller/mitc#45]
My suggestion would be to register the software in Zenodo or 4TU the moment we have our first stable release

**Comment by mwakok** [comment]
The steps we need to follow to create a DOI on Zenodo are described in this [guide](https://guides.github.com/activities/citable-code/). For step-by-step walkthough, you can also watch this short [video](https://www.youtube.com/watch?v=pjsbBQYOOaE&ab_channel=OpenScienceMOOC). After linking Zenodo to the repository, each new release on GitHub will be archieved (not the current ones). 

I have connected Zenodo to the repository, and deleted and recreated our latest release in order for Zenodo to archive it. Before we publish it, we need to check the metadata (contributors, grants, etc.). @omarkamouh Can you login to Zenodo with your GitHub account and check whether you can access the archive?

**Comment by omarkamouh** [comment]
@mwakok I could access it. I found this  https://doi.org/10.5281/zenodo.4507337
Is that all? Is it now necessary to also include the link to the repository?

**Comment by mwakok** [comment]
@omarkamouh 

1) Yes, that's a public link I believe. But I would like to make sure you have editing rights on Zenodo to change some of the meta data. Currently, publishing the DOI is not complete yet as I am prompted to provide some details. If you login to Zenodo with your GitHub account, and then go "Uploads". Do you see anything? Or if you click on the arrow next to your email address (top right), do you see the repository as an _enabled repository_?

2) It is not necessary to include the link in the repository, just good practice. This link in the repository will always point to the latest archieved version.

**Comment by mwakok** [comment]
ToDo: look into transferring Zenodo admin privileges
