### ISSUE TITLE
Set initial simulation parameters on the basis of the project data

### ISSUE THREAD

**Issue by omarkamouh** [mitigation-controller/mitc#47]

**Comment by mwakok** [comment]
- [ ]  Change order GUI layout: 1) Load data 2) User inputs
- [ ] Add uneditable field for Orginal duration (Target duration < original duration)
- [ ] Run `generate_paths.m` and `select_critical_paths.m` as Load callback
- [ ] Update Oringal duration from app.Data.T_orig
