### ISSUE TITLE
Predecessor activtities 

### ISSUE THREAD

**Issue by marieke28** [mitigation-controller/mitc#91]
Is there a way to fill in finish to start, start to start etc. in the predecessors colomn instead of only link the end the activities? And if not, is there a way to fix this? 

For example predecessors like this?
175SF+1d
136
174
175SS-2d
175
177
178

Thanks!

**Comment by mwakok** [comment]
@omarkamouh Could you have a look at this issue?

**Comment by omarkamouh** [comment]
That is not possible. The software only supports finish to start.
